// EN → DE Mapping für Länder-/Nationalmannschafts-Namen.
//
// api-football.com liefert Team-Namen in Englisch. Wir übersetzen nur an den
// UI-Stellen, nicht in der DB, damit beim Fixture-Import keine Normalisierung
// nötig ist und Name-Änderungen (api-football schickt z.B. manchmal "Czech
// Republic", manchmal "Czechia") nicht zu Datenmüll führen.
//
// Unbekannte Namen fallen auf das Original zurück — dadurch bricht nichts,
// wenn ein Exot (Neuqualifikant, "TBD", Playoff-Tag) reinkommt.

const EN_TO_DE: Readonly<Record<string, string>> = {
  // UEFA
  Germany: 'Deutschland',
  England: 'England',
  Scotland: 'Schottland',
  Wales: 'Wales',
  'Northern Ireland': 'Nordirland',
  Ireland: 'Irland',
  'Republic of Ireland': 'Irland',
  France: 'Frankreich',
  Spain: 'Spanien',
  Italy: 'Italien',
  Portugal: 'Portugal',
  Netherlands: 'Niederlande',
  Belgium: 'Belgien',
  Switzerland: 'Schweiz',
  Austria: 'Österreich',
  Croatia: 'Kroatien',
  Serbia: 'Serbien',
  Poland: 'Polen',
  'Czech Republic': 'Tschechien',
  Czechia: 'Tschechien',
  Slovakia: 'Slowakei',
  Slovenia: 'Slowenien',
  Hungary: 'Ungarn',
  Romania: 'Rumänien',
  Bulgaria: 'Bulgarien',
  Greece: 'Griechenland',
  Turkey: 'Türkei',
  Türkiye: 'Türkei',
  Denmark: 'Dänemark',
  Sweden: 'Schweden',
  Norway: 'Norwegen',
  Finland: 'Finnland',
  Iceland: 'Island',
  Ukraine: 'Ukraine',
  Russia: 'Russland',
  Belarus: 'Belarus',
  Albania: 'Albanien',
  'North Macedonia': 'Nordmazedonien',
  'Bosnia and Herzegovina': 'Bosnien und Herzegowina',
  Bosnia: 'Bosnien',
  Montenegro: 'Montenegro',
  Kosovo: 'Kosovo',
  Luxembourg: 'Luxemburg',
  Latvia: 'Lettland',
  Lithuania: 'Litauen',
  Estonia: 'Estland',
  Moldova: 'Moldau',
  Malta: 'Malta',
  Cyprus: 'Zypern',
  Georgia: 'Georgien',
  Armenia: 'Armenien',
  Azerbaijan: 'Aserbaidschan',
  Kazakhstan: 'Kasachstan',
  Andorra: 'Andorra',
  Liechtenstein: 'Liechtenstein',
  'San Marino': 'San Marino',
  Gibraltar: 'Gibraltar',
  'Faroe Islands': 'Färöer',

  // CONMEBOL
  Brazil: 'Brasilien',
  Argentina: 'Argentinien',
  Uruguay: 'Uruguay',
  Chile: 'Chile',
  Colombia: 'Kolumbien',
  Peru: 'Peru',
  Ecuador: 'Ecuador',
  Paraguay: 'Paraguay',
  Bolivia: 'Bolivien',
  Venezuela: 'Venezuela',

  // CONCACAF
  'United States': 'USA',
  USA: 'USA',
  Mexico: 'Mexiko',
  Canada: 'Kanada',
  'Costa Rica': 'Costa Rica',
  Panama: 'Panama',
  Honduras: 'Honduras',
  Jamaica: 'Jamaika',
  Cuba: 'Kuba',
  Haiti: 'Haiti',
  'El Salvador': 'El Salvador',
  Guatemala: 'Guatemala',
  Nicaragua: 'Nicaragua',
  'Trinidad and Tobago': 'Trinidad und Tobago',
  'Dominican Republic': 'Dominikanische Republik',
  Curaçao: 'Curaçao',
  Curacao: 'Curaçao',
  Martinique: 'Martinique',
  Suriname: 'Suriname',
  Guyana: 'Guyana',

  // CAF
  Morocco: 'Marokko',
  Tunisia: 'Tunesien',
  Algeria: 'Algerien',
  Egypt: 'Ägypten',
  'South Africa': 'Südafrika',
  Nigeria: 'Nigeria',
  Ghana: 'Ghana',
  Senegal: 'Senegal',
  Cameroon: 'Kamerun',
  'Ivory Coast': 'Elfenbeinküste',
  "Côte d'Ivoire": 'Elfenbeinküste',
  Mali: 'Mali',
  'Burkina Faso': 'Burkina Faso',
  Guinea: 'Guinea',
  Togo: 'Togo',
  Benin: 'Benin',
  Niger: 'Niger',
  Chad: 'Tschad',
  'Cape Verde': 'Kap Verde',
  Comoros: 'Komoren',
  'Central African Republic': 'Zentralafrikanische Republik',
  Madagascar: 'Madagaskar',
  Mauritania: 'Mauretanien',
  Rwanda: 'Ruanda',
  Gabon: 'Gabun',
  'Equatorial Guinea': 'Äquatorialguinea',
  Libya: 'Libyen',
  Sudan: 'Sudan',
  Ethiopia: 'Äthiopien',
  Kenya: 'Kenia',
  Angola: 'Angola',
  Mozambique: 'Mosambik',
  Zambia: 'Sambia',
  Zimbabwe: 'Simbabwe',
  Uganda: 'Uganda',
  Tanzania: 'Tansania',
  'DR Congo': 'DR Kongo',
  'Democratic Republic of Congo': 'DR Kongo',
  Congo: 'Kongo',
  'Sierra Leone': 'Sierra Leone',
  Liberia: 'Liberia',
  Gambia: 'Gambia',
  'Guinea-Bissau': 'Guinea-Bissau',
  Namibia: 'Namibia',
  Botswana: 'Botswana',
  Eswatini: 'Eswatini',
  Lesotho: 'Lesotho',
  Malawi: 'Malawi',

  // AFC
  Japan: 'Japan',
  'South Korea': 'Südkorea',
  Korea: 'Südkorea',
  'Korea Republic': 'Südkorea',
  'North Korea': 'Nordkorea',
  Iran: 'Iran',
  'IR Iran': 'Iran',
  Iraq: 'Irak',
  'Saudi Arabia': 'Saudi-Arabien',
  Qatar: 'Katar',
  'United Arab Emirates': 'VAE',
  UAE: 'VAE',
  Bahrain: 'Bahrain',
  Kuwait: 'Kuwait',
  Oman: 'Oman',
  Jordan: 'Jordanien',
  Lebanon: 'Libanon',
  Syria: 'Syrien',
  Palestine: 'Palästina',
  Yemen: 'Jemen',
  Australia: 'Australien',
  'New Zealand': 'Neuseeland',
  China: 'China',
  'China PR': 'China',
  India: 'Indien',
  Thailand: 'Thailand',
  Vietnam: 'Vietnam',
  Indonesia: 'Indonesien',
  Malaysia: 'Malaysia',
  Singapore: 'Singapur',
  Philippines: 'Philippinen',
  Uzbekistan: 'Usbekistan',
  Turkmenistan: 'Turkmenistan',
  Kyrgyzstan: 'Kirgisistan',
  Tajikistan: 'Tadschikistan',
  Afghanistan: 'Afghanistan',
  Pakistan: 'Pakistan',
  Bangladesh: 'Bangladesch',
  'Sri Lanka': 'Sri Lanka',
  Nepal: 'Nepal',
  Maldives: 'Malediven',
  Mongolia: 'Mongolei',
  Myanmar: 'Myanmar',
  Cambodia: 'Kambodscha',
  Laos: 'Laos',
  'Hong Kong': 'Hongkong',
  Taiwan: 'Taiwan',
  'Chinese Taipei': 'Chinesisch Taipeh',

  // OFC
  Fiji: 'Fidschi',
  Tahiti: 'Tahiti',
  'Papua New Guinea': 'Papua-Neuguinea',
  'Solomon Islands': 'Salomonen',
  Vanuatu: 'Vanuatu',
  'New Caledonia': 'Neukaledonien',
  Samoa: 'Samoa',
  Tonga: 'Tonga',

  // Sonstige/Sonderfälle
  Israel: 'Israel',
  TBD: 'TBD',
};

/**
 * Übersetzt einen englischen Länder-/Nationalteam-Namen ins Deutsche.
 * Unbekannte Namen werden unverändert zurückgegeben.
 */
export function deName(en: string | null | undefined): string {
  if (!en) return '';
  return EN_TO_DE[en] ?? en;
}
